export const NEWS_FETCH_DATA_SUCCESS = 'NEWS_FETCH_DATA_SUCCESS';
export const NEWS_IS_LOADING = 'NEWS_IS_LOADING';
export const NEWS_HAS_ERRORED = 'NEWS_HAS_ERRORED';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_OUT = 'LOG_OUT';